name: Spec-Kit CI Gates

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

concurrency:
  group: speckit-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  speckit-gates:
    name: Spec-Kit Phase Gates
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@lishavarughese-private:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Run gate evaluation
        id: gates
        run: |
          mkdir -p ci-reports
          node scripts/speckit.js gate --auto --html 2>&1 | tee ci-reports/gate-output.txt
          echo "EXIT_CODE=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Check gate exit code
        id: check
        run: |
          CODE=${{ steps.gates.outputs.EXIT_CODE }}
          if [ "$CODE" = "0" ]; then
            echo "HARD_RESULT=PASS" >> $GITHUB_OUTPUT
          else
            echo "HARD_RESULT=FAIL" >> $GITHUB_OUTPUT
          fi

      - name: Upload CI reports as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: speckit-ci-reports
          path: ci-reports/
          retention-days: 90

      - name: Post gate report as PR comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const reportsDir = 'ci-reports';
            let htmlContent = '';
            let jsonContent = null;
            for (const phase of ['IMPL', 'TASKS', 'PLAN', 'SPEC']) {
              const h = path.join(reportsDir, phase + '-gate-report-latest.html');
              const j = path.join(reportsDir, phase + '-gate-report-latest.json');
              if (fs.existsSync(h)) {
                htmlContent = fs.readFileSync(h, 'utf8');
                jsonContent = JSON.parse(fs.readFileSync(j, 'utf8'));
                break;
              }
            }

            const hardResult = jsonContent ? (jsonContent.transition_allowed ? 'PASS' : 'FAIL') : 'UNKNOWN';
            const hIcon  = hardResult === 'PASS' ? '\u2705' : '\u26D4';
            const s = jsonContent ? jsonContent.summary : {};

            const body = `## \u{1F3DB}\uFE0F Spec-Kit CI Gate Report

            ### ${hIcon} Hard Gate: ${hardResult}
            > ${s.passed || 0}/${s.total_gates || 0} gates passed | ${s.hard_failures || 0} failure(s)

            <details>
            <summary>\uD83D\uDCC4 View Full HTML Report</summary>

            \`\`\`html
            ${htmlContent}
            \`\`\`

            </details>

            ${hardResult === 'PASS'
              ? '### \u2705 All Gates Passed\nThis PR is ready for review.'
              : '### \u26D4 Merge is BLOCKED\nFix all hard gate violations and push a new commit.'
            }

            *Generated by speckit.js CI*`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const existing = comments.find(c => c.body.includes('Spec-Kit CI Gate Report'));

            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Fail job if hard gate failed
        if: steps.check.outputs.HARD_RESULT == 'FAIL'
        run: |
          echo "\u26D4 Spec-Kit CI hard gate FAILED. Merge is blocked."
          exit 1
